#! /bin/bash

hosts=($(cat log.txt| cut -f1,10 -d" " | grep -v "-" |awk '{sum[$1]+= $2;}END{for (date in sum){print date,sum[date];}}' | sort -n -r  -k2 | head -10 | cut -f1 -d" "))
numberofbyte=($(cat log.txt| cut -f1,10 -d" " | grep -v "-" |awk '{sum[$1]+= $2;}END{for (date in sum){print date,sum[date];}}' | sort -n -r  -k2 | head -10 |  cut -f2 -d" "))
sum=0;

for element in "${numberofbyte[@]}";
do
	sum=$((element + sum)) 
done
for ((i=0;i<10;i++)); 
do
	percent=$((numberofbyte[i]*100/sum))
  	echo  
